---

- hosts: vagrant
  become: yes
  tasks:
  - name: Installing python dependencies
    apt:
      name: 
        - python-setuptools
        - python3-pip
        - virtualenv
        - libpq-dev
        - python3-psycopg2
      state: present
      update_cache: yes
    become: true
  - name: Add an Apt signing key
    apt_key:
      url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
      state: present
  - apt_repository:
      repo: deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main
      state: present
  - name: install postgresql
    apt:
      name: postgresql-11
      state: present
      update_cache: yes
    become: true

- hosts: vagrant
  become: yes
  roles:
  - postgres